name: Format Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Check formatting
        run: bun fmt:check
